### ISSUE TITLE
prior with multiple covariates doesn't seem to work

### ISSUE THREAD

**Issue by acannistra** [goldingn/GRaF#13]
From the [documentation](https://cran.r-project.org/web/packages/GRaF/GRaF.pdf), we see that it is possible to provide a prior estimate of presence probability given a vector of environmental covariates, but trying this results in the following error: 

    Error in while (obj.old - obj > tol & it < itmax) { : 
      missing value where TRUE/FALSE needed

You can see our code (line 185) [here](https://github.com/HuckleyLab/SDMpriors/blob/master/SDMpriors.R#L185).

The package works well otherwise, using priors on single environmental variables.

Any advice is appreciated.

**Comment by goldingn** [comment]
Hi Tony. 

I'm a bit confused by your function. The prior argument has to be a function that takes a dataframe (of all covariates) and returns a vector of probability of presence for each row in the dataframe.

You use cbind, which returns either a matrix or dataframe, right?

Sorry if I missed something.

**Comment by acannistra** [comment]
Oh, I see. For example, if we have environmental covariates A, B, and C, the prior function produces a _single_ probability of presence given the three covariates, rather than a probability given each of the covariates individually? Would it be possible for you to give an example?

**Comment by goldingn** [comment]
That's correct. It's an *a priori* guess at the SDM function. There's an example here: https://github.com/goldingn/gp_sdm_paper/blob/master/figures/fig1_2.R#L63

**Comment by acannistra** [comment]
Ok, great. Thanks for your help!

**Comment by goldingn** [comment]
No problem!
