### ISSUE TITLE
`theta.prior` doesn't do anything

### ISSUE THREAD

**Issue by davharris** [goldingn/GRaF#5]
I believe that `theta.prior` should contribute to `nlposterior`.  It appears not to do so.  

As a result, I get exactly the same lengthscale values regardless of `theta.prior.pars`.

```
library(GRaF)

N = 8

set.seed(1)
x = data.frame(rnorm(N), rnorm(N))
y = rbinom(N, size = 1, prob = 0.5)

g = graf(y = y, x = x)
g0 = graf(y = y, x = x, theta.prior.pars=c(1, 1E-10)) # should force the lengthscale to be 1

g$ls
g0$ls
```

**Comment by bioinfonm** [comment]
Yes, will do. I was having all kinds of trouble with github's Issues last night.
